[package]
name = "lambda-handle-game-actions"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "1.0.0"
lambda_runtime = "0.13"
redis = "1.0.3"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }

tokio = { version = "1", features = ["macros"] }
