[package]
name = "lambda-handle-game-actions"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "1.0.0"
lambda_runtime = "0.13"
serde_json = "1.0"

tokio = { version = "1", features = ["macros"] }
